export type Talent = {
  slug: string;
  name: string;
  role: string;
  rank: string;
  price: string;
  location: string;
  qualification: string;
  stack: string[];
  remark: string;
  summary: string;
  email: string;
  phone: string;
  experience: string;
  portfolio: string;
  socialLinks: {
    label: string;
    url: string;
  }[];
  projects: {
    name: string;
    description: string;
    stack: string[];
  }[];
};

export const talents: Talent[] = [
  {
    slug: "ada-owen",
    name: "Ada Owen",
    role: "Full-stack Creator",
    rank: "Elite",
    price: "$750",
    location: "Lagos, Nigeria",
    qualification: "BSc Computer Science",
    stack: ["Next.js", "Node.js", "PostgreSQL", "Tailwind"],
    remark: "Strong product builder with clean UI taste and reliable API delivery.",
    summary: "Builds end-to-end products for startups with a focus on speed and polished UX.",
    email: "ada.owen@example.com",
    phone: "+234 801 234 5678",
    experience: "4+ years",
    portfolio: "https://portfolio.example.com/ada-owen",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/adaowen" },
      { label: "LinkedIn", url: "https://linkedin.com/in/adaowen" },
      { label: "X", url: "https://x.com/adaowen" },
    ],
    projects: [
      {
        name: "VendorFlow",
        description: "Marketplace dashboard with payments, roles, and live order tracking.",
        stack: ["Next.js", "Prisma", "PostgreSQL"],
      },
      {
        name: "Pulse CRM",
        description: "Simple CRM for small teams with pipeline and analytics views.",
        stack: ["React", "Node.js", "Tailwind"],
      },
    ],
  },
  {
    slug: "mike-ade",
    name: "Mike Ade",
    role: "Full-stack Creator",
    rank: "Pro",
    price: "$520",
    location: "Abuja, Nigeria",
    qualification: "BEng Software Engineering",
    stack: ["React", "Express", "MongoDB", "TypeScript"],
    remark: "Solid on dashboards, auth flows, and fast feature shipping.",
    summary: "Good fit for internal tools, admin panels, and MVPs that need a steady hand.",
    email: "mike.ade@example.com",
    phone: "+234 802 987 1122",
    experience: "3+ years",
    portfolio: "https://portfolio.example.com/mike-ade",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/mikeade" },
      { label: "LinkedIn", url: "https://linkedin.com/in/mikeade" },
    ],
    projects: [
      {
        name: "Ops Desk",
        description: "Internal admin panel for managing tickets and staff records.",
        stack: ["React", "Express", "MongoDB"],
      },
      {
        name: "HireLens",
        description: "Hiring workflow app with interview scheduling and notes.",
        stack: ["Next.js", "TypeScript", "Supabase"],
      },
    ],
  },
  {
    slug: "sade-kelvin",
    name: "Sade Kelvin",
    role: "Full-stack Creator",
    rank: "Senior",
    price: "$900",
    location: "Remote",
    qualification: "MSc Information Systems",
    stack: ["Next.js", "Prisma", "Supabase", "Framer Motion"],
    remark: "Works well on premium landing pages and SaaS frontends with sharp attention to detail.",
    summary: "Best for teams that need a creator who can design, build, and refine without hand-holding.",
    email: "sade.kelvin@example.com",
    phone: "+1 555 201 4488",
    experience: "6+ years",
    portfolio: "https://portfolio.example.com/sade-kelvin",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/sadekelvin" },
      { label: "LinkedIn", url: "https://linkedin.com/in/sadekelvin" },
      { label: "Dribbble", url: "https://dribbble.com/sadekelvin" },
    ],
    projects: [
      {
        name: "Atlas SaaS",
        description: "Premium SaaS frontend with auth, pricing, and dashboards.",
        stack: ["Next.js", "Prisma", "Framer Motion"],
      },
      {
        name: "Nova Studio",
        description: "Creative agency website with CMS content and motion design.",
        stack: ["Next.js", "Tailwind", "Contentful"],
      },
    ],
  },
  {
    slug: "chioma-nelson",
    name: "Chioma Nelson",
    role: "Full-stack Creator",
    rank: "Growth",
    price: "$390",
    location: "Port Harcourt, Nigeria",
    qualification: "BSc Software Engineering",
    stack: ["React", "Firebase", "CSS", "API Integration"],
    remark: "Best for straightforward builds, integrations, and polished MVP execution.",
    summary: "Ideal for businesses that need practical delivery without heavy process.",
    email: "chioma.nelson@example.com",
    phone: "+234 803 445 7788",
    experience: "2+ years",
    portfolio: "https://portfolio.example.com/chioma-nelson",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/chiomanelson" },
      { label: "LinkedIn", url: "https://linkedin.com/in/chiomanelson" },
    ],
    projects: [
      {
        name: "QuickBooks Lite",
        description: "Simple invoicing app with user login and export features.",
        stack: ["React", "Firebase", "CSS"],
      },
      {
        name: "Campus Connect",
        description: "Student community portal with announcements and profiles.",
        stack: ["Next.js", "API Integration", "Tailwind"],
      },
    ],
  },
  {
    slug: "dara-cole",
    name: "Dara Cole",
    role: "Full-stack Creator",
    rank: "Pro",
    price: "$610",
    location: "Remote",
    qualification: "BSc Computer Engineering",
    stack: ["Next.js", "Node.js", "MongoDB", "Shadcn"],
    remark: "Balanced builder for product pages, auth, and backend wiring.",
    summary: "Strong on clean interfaces and dependable CRUD-heavy applications.",
    email: "dara.cole@example.com",
    phone: "+1 555 210 3301",
    experience: "4+ years",
    portfolio: "https://portfolio.example.com/dara-cole",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/daracole" },
      { label: "LinkedIn", url: "https://linkedin.com/in/daracole" },
    ],
    projects: [
      {
        name: "FlowDesk",
        description: "Ops dashboard for tickets, customers, and invoice statuses.",
        stack: ["Next.js", "Node.js", "MongoDB"],
      },
      {
        name: "BrightDocs",
        description: "Internal documentation portal with search and markdown content.",
        stack: ["React", "TypeScript", "Tailwind"],
      },
    ],
  },
  {
    slug: "jide-ross",
    name: "Jide Ross",
    role: "Full-stack Creator",
    rank: "Senior",
    price: "$880",
    location: "Lagos, Nigeria",
    qualification: "MSc Software Engineering",
    stack: ["React", "NestJS", "PostgreSQL", "Redis"],
    remark: "Excellent for larger systems, cleaner architecture, and performance-sensitive work.",
    summary: "Good fit for teams that want a senior hand on product architecture.",
    email: "jide.ross@example.com",
    phone: "+234 810 222 0911",
    experience: "7+ years",
    portfolio: "https://portfolio.example.com/jide-ross",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/jideross" },
      { label: "LinkedIn", url: "https://linkedin.com/in/jideross" },
      { label: "X", url: "https://x.com/jideross" },
    ],
    projects: [
      {
        name: "LedgerCore",
        description: "Finance dashboard with audit logs and RBAC.",
        stack: ["NestJS", "PostgreSQL", "Redis"],
      },
      {
        name: "CloudHire",
        description: "Hiring platform with search, profiles, and reporting.",
        stack: ["React", "TypeScript", "PostgreSQL"],
      },
    ],
  },
  {
    slug: "tola-adepoju",
    name: "Tola Adepoju",
    role: "Full-stack Creator",
    rank: "Growth",
    price: "$430",
    location: "Ibadan, Nigeria",
    qualification: "BSc Information Technology",
    stack: ["React", "Firebase", "Next.js", "Vercel"],
    remark: "Fast on landing pages, forms, and practical startup builds.",
    summary: "Useful for early-stage teams needing quick progress and solid UX.",
    email: "tola.adepoju@example.com",
    phone: "+234 812 404 5500",
    experience: "3+ years",
    portfolio: "https://portfolio.example.com/tola-adepoju",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/tolaadepoju" },
      { label: "LinkedIn", url: "https://linkedin.com/in/tolaadepoju" },
    ],
    projects: [
      {
        name: "SprintLaunch",
        description: "Startup landing page with lead capture and email integration.",
        stack: ["Next.js", "Tailwind", "Firebase"],
      },
      {
        name: "StudyBoard",
        description: "Student task tracker with simple analytics.",
        stack: ["React", "Firebase", "TypeScript"],
      },
    ],
  },
  {
    slug: "kemi-ade",
    name: "Kemi Ade",
    role: "Full-stack Creator",
    rank: "Elite",
    price: "$970",
    location: "Remote",
    qualification: "BSc Computer Science",
    stack: ["Next.js", "GraphQL", "PostgreSQL", "Stripe"],
    remark: "Good for premium customer-facing products and revenue-oriented flows.",
    summary: "Handles sharp UI and end-to-end logic with low friction.",
    email: "kemi.ade@example.com",
    phone: "+1 555 811 7722",
    experience: "6+ years",
    portfolio: "https://portfolio.example.com/kemi-ade",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/kemiade" },
      { label: "LinkedIn", url: "https://linkedin.com/in/kemiade" },
      { label: "X", url: "https://x.com/kemiade" },
    ],
    projects: [
      {
        name: "PayNest",
        description: "Subscription billing app with usage plans and invoicing.",
        stack: ["Next.js", "GraphQL", "Stripe"],
      },
      {
        name: "MarketSense",
        description: "Analytics-driven product site with conversion dashboards.",
        stack: ["Next.js", "PostgreSQL", "Tailwind"],
      },
    ],
  },
  {
    slug: "femi-olatunji",
    name: "Femi Olatunji",
    role: "Full-stack Creator",
    rank: "Pro",
    price: "$560",
    location: "Abeokuta, Nigeria",
    qualification: "HND Computer Science",
    stack: ["React", "Node.js", "Express", "MySQL"],
    remark: "Reliable on standard business apps and admin workflows.",
    summary: "Ideal when you need dependable execution and decent speed.",
    email: "femi.olatunji@example.com",
    phone: "+234 814 330 1188",
    experience: "4+ years",
    portfolio: "https://portfolio.example.com/femi-olatunji",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/femiolatunji" },
      { label: "LinkedIn", url: "https://linkedin.com/in/femiolatunji" },
    ],
    projects: [
      {
        name: "TaskHive",
        description: "Task management app for internal team operations.",
        stack: ["React", "Node.js", "MySQL"],
      },
      {
        name: "StorePilot",
        description: "Retail operations app with stock alerts and invoices.",
        stack: ["Express", "MySQL", "Tailwind"],
      },
    ],
  },
  {
    slug: "ayo-bello",
    name: "Ayo Bello",
    role: "Full-stack Creator",
    rank: "Senior",
    price: "$820",
    location: "Remote",
    qualification: "BEng Computer Engineering",
    stack: ["Next.js", "Prisma", "PostgreSQL", "Docker"],
    remark: "Solid engineering standards and strong product thinking.",
    summary: "Good for teams that care about architecture and long-term maintainability.",
    email: "ayo.bello@example.com",
    phone: "+1 555 448 9901",
    experience: "8+ years",
    portfolio: "https://portfolio.example.com/ayo-bello",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/ayobello" },
      { label: "LinkedIn", url: "https://linkedin.com/in/ayobello" },
    ],
    projects: [
      {
        name: "CoreOps",
        description: "Enterprise ops app with role-based access control.",
        stack: ["Next.js", "Prisma", "PostgreSQL"],
      },
      {
        name: "FleetBoard",
        description: "Fleet monitoring dashboard with maps and alerts.",
        stack: ["React", "Docker", "PostgreSQL"],
      },
    ],
  },
  {
    slug: "temi-khan",
    name: "Temi Khan",
    role: "Full-stack Creator",
    rank: "Growth",
    price: "$460",
    location: "Remote",
    qualification: "BSc Computer Science",
    stack: ["React", "Supabase", "Tailwind", "TypeScript"],
    remark: "Quick and clean on MVPs, onboarding, and user portals.",
    summary: "A practical choice for early product builds and fast iteration.",
    email: "temi.khan@example.com",
    phone: "+1 555 400 7702",
    experience: "3+ years",
    portfolio: "https://portfolio.example.com/temi-khan",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/temikhan" },
      { label: "LinkedIn", url: "https://linkedin.com/in/temikhan" },
      { label: "X", url: "https://x.com/temikhan" },
    ],
    projects: [
      {
        name: "Onboardly",
        description: "User onboarding portal with feature tours and email capture.",
        stack: ["React", "Supabase", "Tailwind"],
      },
      {
        name: "LaunchPad",
        description: "Fast SaaS starter with auth and role separation.",
        stack: ["Next.js", "TypeScript", "Supabase"],
      },
    ],
  },
  {
    slug: "ibrahim-ade",
    name: "Ibrahim Ade",
    role: "Full-stack Creator",
    rank: "Pro",
    price: "$510",
    location: "Kano, Nigeria",
    qualification: "BSc Software Engineering",
    stack: ["Next.js", "Node.js", "PostgreSQL", "Tailwind"],
    remark: "Strong on responsive interfaces and service integrations.",
    summary: "Good fit for content-heavy products and clean dashboards.",
    email: "ibrahim.ade@example.com",
    phone: "+234 815 900 3344",
    experience: "4+ years",
    portfolio: "https://portfolio.example.com/ibrahim-ade",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/ibrahimade" },
      { label: "LinkedIn", url: "https://linkedin.com/in/ibrahimade" },
    ],
    projects: [
      {
        name: "SchoolDesk",
        description: "School management portal with attendance and results.",
        stack: ["Next.js", "PostgreSQL", "Tailwind"],
      },
      {
        name: "MediaPilot",
        description: "Content publishing dashboard with role controls.",
        stack: ["Node.js", "PostgreSQL", "React"],
      },
    ],
  },
  {
    slug: "nneka-simon",
    name: "Nneka Simon",
    role: "Full-stack Creator",
    rank: "Elite",
    price: "$990",
    location: "Remote",
    qualification: "MSc Computer Science",
    stack: ["Next.js", "NestJS", "PostgreSQL", "AWS"],
    remark: "High-end delivery with strong product judgment and consistent code quality.",
    summary: "Best for serious product teams that want top-tier execution.",
    email: "nneka.simon@example.com",
    phone: "+1 555 604 8810",
    experience: "9+ years",
    portfolio: "https://portfolio.example.com/nneka-simon",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/nnekasimon" },
      { label: "LinkedIn", url: "https://linkedin.com/in/nnekasimon" },
      { label: "X", url: "https://x.com/nnekasimon" },
    ],
    projects: [
      {
        name: "Atlas Pay",
        description: "Payments platform with account controls and reporting.",
        stack: ["Next.js", "NestJS", "AWS"],
      },
      {
        name: "SignalPro",
        description: "Real-time analytics suite for operational teams.",
        stack: ["PostgreSQL", "AWS", "TypeScript"],
      },
    ],
  },
  {
    slug: "segun-bala",
    name: "Segun Bala",
    role: "Full-stack Creator",
    rank: "Senior",
    price: "$760",
    location: "Abuja, Nigeria",
    qualification: "BSc Information Systems",
    stack: ["React", "Node.js", "PostgreSQL", "Redis"],
    remark: "Great balance of speed, structure, and business-friendly implementation.",
    summary: "A good match for SaaS, logistics, and client portals.",
    email: "segun.bala@example.com",
    phone: "+234 816 503 2233",
    experience: "7+ years",
    portfolio: "https://portfolio.example.com/segun-bala",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/segunbala" },
      { label: "LinkedIn", url: "https://linkedin.com/in/segunbala" },
    ],
    projects: [
      {
        name: "LogiTrack",
        description: "Delivery tracking dashboard with customer notifications.",
        stack: ["React", "Node.js", "Redis"],
      },
      {
        name: "ClientDesk",
        description: "Client portal with tasks, documents, and approvals.",
        stack: ["Next.js", "PostgreSQL", "Tailwind"],
      },
    ],
  },
  {
    slug: "fatima-bello",
    name: "Fatima Bello",
    role: "Full-stack Creator",
    rank: "Growth",
    price: "$410",
    location: "Remote",
    qualification: "BSc Computer Science",
    stack: ["React", "Firebase", "Next.js", "CSS"],
    remark: "Best for lightweight products, small business tools, and quick launches.",
    summary: "Handles clear builds with a focus on usability.",
    email: "fatima.bello@example.com",
    phone: "+1 555 330 4410",
    experience: "2+ years",
    portfolio: "https://portfolio.example.com/fatima-bello",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/fatimabello" },
      { label: "LinkedIn", url: "https://linkedin.com/in/fatimabello" },
    ],
    projects: [
      {
        name: "MiniMart",
        description: "Small business sales app with product tracking.",
        stack: ["React", "Firebase", "CSS"],
      },
      {
        name: "NoticeBoard",
        description: "Announcement platform with admin posting and subscriptions.",
        stack: ["Next.js", "Firebase", "TypeScript"],
      },
    ],
  },
  {
    slug: "oluwaseun-ade",
    name: "Oluwaseun Ade",
    role: "Full-stack Creator",
    rank: "Pro",
    price: "$540",
    location: "Lagos, Nigeria",
    qualification: "BSc Computer Engineering",
    stack: ["Next.js", "Node.js", "MongoDB", "Zod"],
    remark: "Reliable on structured forms, admin apps, and API-heavy work.",
    summary: "Strong execution for practical business software.",
    email: "oluwaseun.ade@example.com",
    phone: "+234 817 700 4555",
    experience: "4+ years",
    portfolio: "https://portfolio.example.com/oluwaseun-ade",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/oluwaseunade" },
      { label: "LinkedIn", url: "https://linkedin.com/in/oluwaseunade" },
    ],
    projects: [
      {
        name: "FormKit Pro",
        description: "Dynamic form engine for business workflows and approvals.",
        stack: ["Next.js", "Node.js", "MongoDB"],
      },
      {
        name: "CaseVault",
        description: "Client records portal with structured search and filters.",
        stack: ["React", "Zod", "MongoDB"],
      },
    ],
  },
  {
    slug: "bisi-adebayo",
    name: "Bisi Adebayo",
    role: "Full-stack Creator",
    rank: "Elite",
    price: "$930",
    location: "Remote",
    qualification: "BSc Computer Science",
    stack: ["Next.js", "Prisma", "PostgreSQL", "Redis"],
    remark: "Excellent for premium product builds and tight design systems.",
    summary: "Strong product sense, reliable delivery, and polished implementation.",
    email: "bisi.adebayo@example.com",
    phone: "+1 555 899 4402",
    experience: "7+ years",
    portfolio: "https://portfolio.example.com/bisi-adebayo",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/bisiadebayo" },
      { label: "LinkedIn", url: "https://linkedin.com/in/bisiadebayo" },
      { label: "X", url: "https://x.com/bisiadebayo" },
    ],
    projects: [
      {
        name: "StudioCloud",
        description: "Creative platform with workspace, billing, and client views.",
        stack: ["Next.js", "Prisma", "PostgreSQL"],
      },
      {
        name: "SignalHQ",
        description: "Realtime monitoring dashboard with caching and queues.",
        stack: ["Redis", "Prisma", "TypeScript"],
      },
    ],
  },
  {
    slug: "wale-owolabi",
    name: "Wale Owolabi",
    role: "Full-stack Creator",
    rank: "Senior",
    price: "$790",
    location: "Remote",
    qualification: "BEng Software Engineering",
    stack: ["React", "NestJS", "PostgreSQL", "Docker"],
    remark: "Very strong on robust APIs and maintainable app architecture.",
    summary: "Good for products that need dependable backend structure.",
    email: "wale.owolabi@example.com",
    phone: "+1 555 613 2200",
    experience: "8+ years",
    portfolio: "https://portfolio.example.com/wale-owolabi",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/waleowolabi" },
      { label: "LinkedIn", url: "https://linkedin.com/in/waleowolabi" },
    ],
    projects: [
      {
        name: "RouteIQ",
        description: "Logistics app with assignments, drivers, and live status.",
        stack: ["NestJS", "PostgreSQL", "Docker"],
      },
      {
        name: "TeamStack",
        description: "Team collaboration portal with role controls and logs.",
        stack: ["React", "NestJS", "PostgreSQL"],
      },
    ],
  },
  {
    slug: "tobi-richards",
    name: "Tobi Richards",
    role: "Full-stack Creator",
    rank: "Growth",
    price: "$395",
    location: "Ibadan, Nigeria",
    qualification: "HND Computer Science",
    stack: ["React", "Express", "MongoDB", "Tailwind"],
    remark: "Quick to ship and easy to work with on lightweight products.",
    summary: "Useful for simple web apps, form flows, and MVPs.",
    email: "tobi.richards@example.com",
    phone: "+234 818 210 7700",
    experience: "2+ years",
    portfolio: "https://portfolio.example.com/tobi-richards",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/tobirichards" },
      { label: "LinkedIn", url: "https://linkedin.com/in/tobirichards" },
    ],
    projects: [
      {
        name: "QuickHire",
        description: "Tiny recruitment portal with forms and notifications.",
        stack: ["React", "Express", "MongoDB"],
      },
      {
        name: "NoteBoard",
        description: "Personal note app with categories and search.",
        stack: ["React", "Tailwind", "MongoDB"],
      },
    ],
  },
  {
    slug: "lara-onyeka",
    name: "Lara Onyeka",
    role: "Full-stack Creator",
    rank: "Pro",
    price: "$605",
    location: "Remote",
    qualification: "BSc Information Technology",
    stack: ["Next.js", "Prisma", "PostgreSQL", "Tailwind"],
    remark: "Strong on user-facing features and clean responsiveness.",
    summary: "Best for SaaS landing pages and small admin systems.",
    email: "lara.onyeka@example.com",
    phone: "+1 555 228 9010",
    experience: "4+ years",
    portfolio: "https://portfolio.example.com/lara-onyeka",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/laraonyeka" },
      { label: "LinkedIn", url: "https://linkedin.com/in/laraonyeka" },
      { label: "X", url: "https://x.com/laraonyeka" },
    ],
    projects: [
      {
        name: "Boardroom",
        description: "Business admin panel with analytics and role-based access.",
        stack: ["Next.js", "Prisma", "PostgreSQL"],
      },
      {
        name: "Careline",
        description: "Support portal with tickets and reply threads.",
        stack: ["Tailwind", "TypeScript", "PostgreSQL"],
      },
    ],
  },
  {
    slug: "kola-farouk",
    name: "Kola Farouk",
    role: "Full-stack Creator",
    rank: "Senior",
    price: "$845",
    location: "Lagos, Nigeria",
    qualification: "MSc Software Engineering",
    stack: ["Next.js", "NestJS", "PostgreSQL", "AWS"],
    remark: "A senior builder for products that need stable scaling decisions.",
    summary: "Good for teams moving from prototype to mature product.",
    email: "kola.farouk@example.com",
    phone: "+234 819 991 1120",
    experience: "7+ years",
    portfolio: "https://portfolio.example.com/kola-farouk",
    socialLinks: [
      { label: "GitHub", url: "https://github.com/kolafarouk" },
      { label: "LinkedIn", url: "https://linkedin.com/in/kolafarouk" },
    ],
    projects: [
      {
        name: "ScaleBase",
        description: "Product platform with accounts, billing, and monitoring.",
        stack: ["Next.js", "NestJS", "AWS"],
      },
      {
        name: "OpsRadar",
        description: "Operations dashboard for alerts and status updates.",
        stack: ["PostgreSQL", "AWS", "TypeScript"],
      },
    ],
  },
];
